# -------------------------------------------------------------------------
#
#   CONFIGS
#
#     xxx
#
#     Authors:
#       - @amanmajid
#
# -------------------------------------------------------------------------

paths:
  brownfield_models: "networks/brownfield/"
  output_model_runs: "outputs/model_runs/" # path to save model run outputs
  path_to_model: '/tza-pypsa/stock_models/Japan'
global_vars:
  year: 2030 # year of the model run
  frequency: 1h # time resolution of the model run (should be 1h for CFE)
  timesteps: 8760 # number of timesteps in the model run (e.g., 24 = 1 day)
  ci_label: C&I # this is a unique identifier for all CFE attributes in the network
  enable_fossil_charging: false # if true, the model will allow batteries to be charged by fossil fuels
  set_global_constraints: false # if true, the model will set global constraints from tza-pypsa (keep False here)
  maximum_excess_export_cfe: 0.20 # maximum fraction of excess electricity that can be sold from C&I asset to grid under CFE scenarios
  maximum_excess_export_res100: 0.20 # maximum fraction of excess electricity that can be sold from C&I asset to grid under annual matching

constraints:
  bus_self_sufficiency: # constraint is set by user
    enable: false
    fraction: 0.6
    buses:
      - 'INDNO'
      - 'INDEA'
  bus_individual_self_sufficiency: # constraints are predefined in network
    enable: false
  policy_targets:
    enable: false
  min_annual_generation:
    enable: false
    generator: 'example01'
    fraction: 0.2
  min_utilisation_links:
    enable: false
    carriers:
      - 'AC'
  max_utilisation_links:
    enable: false
    carriers:
      - 'AC'
  min_utilisation_generator: # fraction is predefined in network
    enable: true
    carriers: 'Biomass'
  max_utilisation_generator: # fraction is predefined in network
    enable: true
    carriers: 'Coal|Geothermal'
  max_utilisation: # fraction is set by user
    enable: false
    fraction: 0.8
    carriers:
      - 'coal'
      - 'gas'
      - 'oil'
      - 'geothermal'
  cofiring_ccs_gen:
    enable: true
    clean_generator: ['JPN01-BlueH2-2030_exo','JPN01-BlueNH3-2030_exo','JPN01-GasCCSSequestered-2030_exo','JPN01-GreenH2-2030_exo','JPN01-GreenNH3-2030_exo','JPN01-BlueH2-2030_endo','JPN01-BlueNH3-2030_endo','JPN01-GasCCSSequestered-2030_endo','JPN01-GreenH2-2030_endo','JPN01-GreenNH3-2030_endo','JPN02-BlueH2-2030_exo','JPN02-BlueNH3-2030_exo','JPN02-GasCCSSequestered-2030_exo','JPN02-GreenH2-2030_exo','JPN02-GreenNH3-2030_exo','JPN02-BlueH2-2030_endo','JPN02-BlueNH3-2030_endo','JPN02-GasCCSSequestered-2030_endo','JPN02-GreenH2-2030_endo','JPN02-GreenNH3-2030_endo','JPN03-BlueH2-2030_exo','JPN03-BlueNH3-2030_exo','JPN03-GasCCSSequestered-2030_exo','JPN03-GreenH2-2030_exo','JPN03-GreenNH3-2030_exo','JPN03-BlueH2-2030_endo','JPN03-BlueNH3-2030_endo','JPN03-GasCCSSequestered-2030_endo','JPN03-GreenH2-2030_endo','JPN03-GreenNH3-2030_endo','JPN04-BlueH2-2030_exo','JPN04-BlueNH3-2030_exo','JPN04-GasCCSSequestered-2030_exo','JPN04-GreenH2-2030_exo','JPN04-GreenNH3-2030_exo','JPN04-BlueH2-2030_endo','JPN04-BlueNH3-2030_endo','JPN04-GasCCSSequestered-2030_endo','JPN04-GreenH2-2030_endo','JPN04-GreenNH3-2030_endo','JPN05-BlueH2-2030_exo','JPN05-BlueNH3-2030_exo','JPN05-GasCCSSequestered-2030_exo','JPN05-GreenH2-2030_exo','JPN05-GreenNH3-2030_exo','JPN05-BlueH2-2030_endo','JPN05-BlueNH3-2030_endo','JPN05-GasCCSSequestered-2030_endo','JPN05-GreenH2-2030_endo','JPN05-GreenNH3-2030_endo','JPN06-BlueH2-2030_exo','JPN06-BlueNH3-2030_exo','JPN06-GasCCSSequestered-2030_exo','JPN06-GreenH2-2030_exo','JPN06-GreenNH3-2030_exo','JPN06-BlueH2-2030_endo','JPN06-BlueNH3-2030_endo','JPN06-GasCCSSequestered-2030_endo','JPN06-GreenH2-2030_endo','JPN06-GreenNH3-2030_endo','JPN07-BlueH2-2030_exo','JPN07-BlueNH3-2030_exo','JPN07-GasCCSSequestered-2030_exo','JPN07-GreenH2-2030_exo','JPN07-GreenNH3-2030_exo','JPN07-BlueH2-2030_endo','JPN07-BlueNH3-2030_endo','JPN07-GasCCSSequestered-2030_endo','JPN07-GreenH2-2030_endo','JPN07-GreenNH3-2030_endo','JPN08-BlueH2-2030_exo','JPN08-BlueNH3-2030_exo','JPN08-GasCCSSequestered-2030_exo','JPN08-GreenH2-2030_exo','JPN08-GreenNH3-2030_exo','JPN08-BlueH2-2030_endo','JPN08-BlueNH3-2030_endo','JPN08-GasCCSSequestered-2030_endo','JPN08-GreenH2-2030_endo','JPN08-GreenNH3-2030_endo','JPN09-BlueH2-2030_exo','JPN09-BlueNH3-2030_exo','JPN09-GasCCSSequestered-2030_exo','JPN09-GreenH2-2030_exo','JPN09-GreenNH3-2030_exo','JPN09-BlueH2-2030_endo','JPN09-BlueNH3-2030_endo','JPN09-GasCCSSequestered-2030_endo','JPN09-GreenH2-2030_endo','JPN09-GreenNH3-2030_endo']
      # - 'JPN01-BlueH2-2030_exo'
      # - 'JPN01-BlueNH3-2030_exo'
      # - 'JPN01-GasCCSSequestered-2030_exo'
      # - 'JPN01-GreenH2-2030_exo'
      # - 'JPN01-GreenNH3-2030_exo'
      # - 'JPN01-BlueH2-2030_endo'
      # - 'JPN01-BlueNH3-2030_endo'
      # - 'JPN01-GasCCSSequestered-2030_endo'
      # - 'JPN01-GreenH2-2030_endo'
      # - 'JPN01-GreenNH3-2030_endo'
      # - 'JPN02-BlueH2-2030_exo'
      # - 'JPN02-BlueNH3-2030_exo'
      # - 'JPN02-GasCCSSequestered-2030_exo'
      # - 'JPN02-GreenH2-2030_exo'
      # - 'JPN02-GreenNH3-2030_exo'
      # - 'JPN02-BlueH2-2030_endo'
      # - 'JPN02-BlueNH3-2030_endo'
      # - 'JPN02-GasCCSSequestered-2030_endo'
      # - 'JPN02-GreenH2-2030_endo'
      # - 'JPN02-GreenNH3-2030_endo'
      # - 'JPN03-BlueH2-2030_exo'
      # - 'JPN03-BlueNH3-2030_exo'
      # - 'JPN03-GasCCSSequestered-2030_exo'
      # - 'JPN03-GreenH2-2030_exo'
      # - 'JPN03-GreenNH3-2030_exo'
      # - 'JPN03-BlueH2-2030_endo'
      # - 'JPN03-BlueNH3-2030_endo'
      # - 'JPN03-GasCCSSequestered-2030_endo'
      # - 'JPN03-GreenH2-2030_endo'
      # - 'JPN03-GreenNH3-2030_endo'
      # - 'JPN04-BlueH2-2030_exo'
      # - 'JPN04-BlueNH3-2030_exo'
      # - 'JPN04-GasCCSSequestered-2030_exo'
      # - 'JPN04-GreenH2-2030_exo'
      # - 'JPN04-GreenNH3-2030_exo'
      # - 'JPN04-BlueH2-2030_endo'
      # - 'JPN04-BlueNH3-2030_endo'
      # - 'JPN04-GasCCSSequestered-2030_endo'
      # - 'JPN04-GreenH2-2030_endo'
      # - 'JPN04-GreenNH3-2030_endo'
      # - 'JPN05-BlueH2-2030_exo'
      # - 'JPN05-BlueNH3-2030_exo'
      # - 'JPN05-GasCCSSequestered-2030_exo'
      # - 'JPN05-GreenH2-2030_exo'
      # - 'JPN05-GreenNH3-2030_exo'
      # - 'JPN05-BlueH2-2030_endo'
      # - 'JPN05-BlueNH3-2030_endo'
      # - 'JPN05-GasCCSSequestered-2030_endo'
      # - 'JPN05-GreenH2-2030_endo'
      # - 'JPN05-GreenNH3-2030_endo'
      # - 'JPN06-BlueH2-2030_exo'
      # - 'JPN06-BlueNH3-2030_exo'
      # - 'JPN06-GasCCSSequestered-2030_exo'
      # - 'JPN06-GreenH2-2030_exo'
      # - 'JPN06-GreenNH3-2030_exo'
      # - 'JPN06-BlueH2-2030_endo'
      # - 'JPN06-BlueNH3-2030_endo'
      # - 'JPN06-GasCCSSequestered-2030_endo'
      # - 'JPN06-GreenH2-2030_endo'
      # - 'JPN06-GreenNH3-2030_endo'
      # - 'JPN07-BlueH2-2030_exo'
      # - 'JPN07-BlueNH3-2030_exo'
      # - 'JPN07-GasCCSSequestered-2030_exo'
      # - 'JPN07-GreenH2-2030_exo'
      # - 'JPN07-GreenNH3-2030_exo'
      # - 'JPN 07-BlueH2-2030_endo'
      # - 'JPN07-BlueNH3-2030_endo'
      # - 'JPN07-GasCCSSequestered-2030_endo'
      # - 'JPN07-GreenH2-2030_endo'
      # - 'JPN07-GreenNH3-2030_endo'
      # - 'JPN08-BlueH2-2030_exo'
      # - 'JPN08-BlueNH3-2030_exo'
      # - 'JPN08-GasCCSSequestered-2030_exo'
      # - 'JPN08-GreenH2-2030_exo'
      # - 'JPN08-GreenNH3-2030_exo'
      # - 'JPN08-BlueH2-2030_endo'
      # - 'JPN08-BlueNH3-2030_endo'
      # - 'JPN08-GasCCSSequestered-2030_endo'
      # - 'JPN08-GreenH2-2030_endo'
      # - 'JPN08-GreenNH3-2030_endo'
      # - 'JPN09-BlueH2-2030_exo'
      # - 'JPN09-BlueNH3-2030_exo'
      # - 'JPN09-GasCCSSequestered-2030_exo'
      # - 'JPN09-GreenH2-2030_exo'
      # - 'JPN09-GreenNH3-2030_exo'
      # - 'JPN09-BlueH2-2030_endo'
      # - 'JPN09-BlueNH3-2030_endo'
      # - 'JPN09-GasCCSSequestered-2030_endo'
      # - 'JPN09-GreenH2-2030_endo'
      # - 'JPN09-GreenNH3-2030_endo'
    fossil_generator: ['JPN01-BlueH2_Gas-2030_exo','JPN01-BlueNH3_Coal-2030_exo','JPN01-GasCCSLeaked-2030_exo','JPN01-GreenH2_Gas-2030_exo','JPN01-GreenNH3_Coal-2030_exo','JPN01-BlueH2_Gas-2030_endo','JPN01-BlueNH3_Coal-2030_endo','JPN01-GasCCSLeaked-2030_endo','JPN01-GreenH2_Gas-2030_endo','JPN01-GreenNH3_Coal-2030_endo','JPN02-BlueH2_Gas-2030_exo','JPN02-BlueNH3_Coal-2030_exo','JPN02-GasCCSLeaked-2030_exo','JPN02-GreenH2_Gas-2030_exo','JPN02-GreenNH3_Coal-2030_exo','JPN02-BlueH2_Gas-2030_endo','JPN02-BlueNH3_Coal-2030_endo','JPN02-GasCCSLeaked-2030_endo','JPN02-GreenH2_Gas-2030_endo','JPN02-GreenNH3_Coal-2030_endo','JPN03-BlueH2_Gas-2030_exo','JPN03-BlueNH3_Coal-2030_exo','JPN03-GasCCSLeaked-2030_exo','JPN03-GreenH2_Gas-2030_exo','JPN03-GreenNH3_Coal-2030_exo','JPN03-BlueH2_Gas-2030_endo','JPN03-BlueNH3_Coal-2030_endo','JPN03-GasCCSLeaked-2030_endo','JPN03-GreenH2_Gas-2030_endo','JPN03-GreenNH3_Coal-2030_endo','JPN04-BlueH2_Gas-2030_exo','JPN04-BlueNH3_Coal-2030_exo','JPN04-GasCCSLeaked-2030_exo','JPN04-GreenH2_Gas-2030_exo','JPN04-GreenNH3_Coal-2030_exo','JPN04-BlueH2_Gas-2030_endo','JPN04-BlueNH3_Coal-2030_endo','JPN04-GasCCSLeaked-2030_endo','JPN04-GreenH2_Gas-2030_endo','JPN04-GreenNH3_Coal-2030_endo','JPN05-BlueH2_Gas-2030_exo','JPN05-BlueNH3_Coal-2030_exo','JPN05-GasCCSLeaked-2030_exo','JPN05-GreenH2_Gas-2030_exo','JPN05-GreenNH3_Coal-2030_exo','JPN05-BlueH2_Gas-2030_endo','JPN05-BlueNH3_Coal-2030_endo','JPN05-GasCCSLeaked-2030_endo','JPN05-GreenH2_Gas-2030_endo','JPN05-GreenNH3_Coal-2030_endo','JPN06-BlueH2_Gas-2030_exo','JPN06-BlueNH3_Coal-2030_exo','JPN06-GasCCSLeaked-2030_exo','JPN06-GreenH2_Gas-2030_exo','JPN06-GreenNH3_Coal-2030_exo','JPN06-BlueH2_Gas-2030_endo','JPN06-BlueNH3_Coal-2030_endo','JPN06-GasCCSLeaked-2030_endo','JPN06-GreenH2_Gas-2030_endo','JPN06-GreenNH3_Coal-2030_endo','JPN07-BlueH2_Gas-2030_exo','JPN07-BlueNH3_Coal-2030_exo','JPN07-GasCCSLeaked-2030_exo','JPN07-GreenH2_Gas-2030_exo','JPN07-GreenNH3_Coal-2030_exo','JPN07-BlueH2_Gas-2030_endo','JPN07-BlueNH3_Coal-2030_endo','JPN07-GasCCSLeaked-2030_endo','JPN07-GreenH2_Gas-2030_endo','JPN07-GreenNH3_Coal-2030_endo','JPN08-BlueH2_Gas-2030_exo','JPN08-BlueNH3_Coal-2030_exo','JPN08-GasCCSLeaked-2030_exo','JPN08-GreenH2_Gas-2030_exo','JPN08-GreenNH3_Coal-2030_exo','JPN08-BlueH2_Gas-2030_endo','JPN08-BlueNH3_Coal-2030_endo','JPN08-GasCCSLeaked-2030_endo','JPN08-GreenH2_Gas-2030_endo','JPN08-GreenNH3_Coal-2030_endo','JPN09-BlueH2_Gas-2030_exo','JPN09-BlueNH3_Coal-2030_exo','JPN09-GasCCSLeaked-2030_exo','JPN09-GreenH2_Gas-2030_exo','JPN09-GreenNH3_Coal-2030_exo','JPN09-BlueH2_Gas-2030_endo','JPN09-BlueNH3_Coal-2030_endo','JPN09-GasCCSLeaked-2030_endo','JPN09-GreenH2_Gas-2030_endo','JPN09-GreenNH3_Coal-2030_endo']
      # - 'JPN01-BlueH2_Gas-2030_exo'
      # - 'JPN01-BlueNH3_Coal-2030_exo'
      # - 'JPN01-GasCCSLeaked-2030_exo'
      # - 'JPN01-GreenH2_Gas-2030_exo'
      # - 'JPN01-GreenNH3_Coal-2030_exo'
      # - 'JPN01-BlueH2_Gas-2030_endo'
      # - 'JPN01-BlueNH3_Coal-2030_endo'
      # - 'JPN01-GasCCSLeaked-2030_endo'
      # - 'JPN01-GreenH2_Gas-2030_endo'
      # - 'JPN01-GreenNH3_Coal-2030_endo'
      # - 'JPN02-BlueH2_Gas-2030_exo'
      # - 'JPN02-BlueNH3_Coal-2030_exo'
      # - 'JPN02-GasCCSLeaked-2030_exo'
      # - 'JPN02-GreenH2_Gas-2030_exo'
      # - 'JPN02-GreenNH3_Coal-2030_exo'
      # - 'JPN02-BlueH2_Gas-2030_endo'
      # - 'JPN02-BlueNH3_Coal-2030_endo'
      # - 'JPN02-GasCCSLeaked-2030_endo'
      # - 'JPN02-GreenH2_Gas-2030_endo'
      # - 'JPN02-GreenNH3_Coal-2030_endo'
      # - 'JPN03-BlueH2_Gas-2030_exo'
      # - 'JPN03-BlueNH3_Coal-2030_exo'
      # - 'JPN03-GasCCSLeaked-2030_exo'
      # - 'JPN03-GreenH2_Gas-2030_exo'
      # - 'JPN03-GreenNH3_Coal-2030_exo'
      # - 'JPN03-BlueH2_Gas-2030_endo'
      # - 'JPN03-BlueNH3_Coal-2030_endo'
      # - 'JPN03-GasCCSLeaked-2030_endo'
      # - 'JPN03-GreenH2_Gas-2030_endo'
      # - 'JPN03-GreenNH3_Coal-2030_endo'
      # - 'JPN04-BlueH2_Gas-2030_exo'
      # - 'JPN04-BlueNH3_Coal-2030_exo'
      # - 'JPN04-GasCCSLeaked-2030_exo'
      # - 'JPN04-GreenH2_Gas-2030_exo'
      # - 'JPN04-GreenNH3_Coal-2030_exo'
      # - ' JPN04-BlueH2_Gas-2030_endo'
      # - 'JPN04-BlueNH3_Coal-2030_endo'
      # - 'JPN04-GasCCSLeaked-2030_endo'
      # - 'JPN04-GreenH2_Gas-2030_endo'
      # - 'JPN04-GreenNH3_Coal-2030_endo'
      # - 'JPN05-BlueH2_Gas-2030_exo'
      # - 'JPN05-BlueNH3_Coal-2030_exo'
      # - 'JPN05-GasCCSLeaked-2030_exo'
      # - 'JPN05-GreenH2_Gas-2030_exo'
      # - 'JPN05-GreenNH3_Coal-2030_exo'
      # - 'JPN05-BlueH2_Gas-2030_endo'
      # - 'JPN05-BlueNH3_Coal-2030_endo'
      # - 'JPN05-GasCCSLeaked-2030_endo'
      # - 'JPN05-GreenH2_Gas-2030_endo'
      # - 'JPN05-GreenNH3_Coal-2030_endo'
      # - 'JPN06-BlueH2_Gas-2030_exo'
      # - 'JPN06-BlueNH3_Coal-2030_exo'
      # - 'JPN06-GasCCSLeaked-2030_exo'
      # - 'JPN06-GreenH2_Gas-2030_exo'
      # - 'JPN06-GreenNH3_Coal-2030_exo'
      # - 'JPN06-BlueH2_Gas-2030_endo'
      # - 'JPN06-BlueNH3_Coal-2030_endo'
      # - 'JPN06-GasCCSLeaked-2030_endo'
      # - 'JPN06-GreenH2_Gas-2030_endo'
      # - 'JPN06-GreenNH3_Coal-2030_endo'
      # - 'JPN07-BlueH2_Gas-2030_exo'
      # - 'JPN07-BlueNH3_Coal-2030_exo'
      # - 'JPN07-GasCCSLeaked-2030_exo'
      # - 'JPN07-GreenH2_Gas-2030_exo'
      # - 'JPN07-GreenNH3_Coal-2030_exo'
      # - 'JPN07-BlueH2_Gas-2030_endo'
      # - 'JPN07-BlueNH3_Coal-2030_endo'
      # - 'JPN07-GasCCSLeaked-2030_endo'
      # - 'JPN07-GreenH2_Gas-2030_endo'
      # - 'JPN07-GreenNH3_Coal-2030_endo'
      # - 'JPN08-BlueH2_Gas-2030_exo'
      # - 'JPN08-BlueNH3_Coal-2030_exo'
      # - 'JPN08-GasCCSLeaked-2030_exo'
      # - 'JPN08-GreenH2_Gas-2030_exo'
      # - 'JPN08-GreenNH3_Coal-2030_exo'
      # - 'JPN08-BlueH2_Gas-2030_endo'
      # - 'JPN08-BlueNH3_Coal-2030_endo'
      # - 'JPN08-GasCCSLeaked-2030_endo'
      # - 'JPN08-GreenH2_Gas-2030_endo'
      # - 'JPN08-GreenNH3_Coal-2030_endo'
      # - 'JPN09-BlueH2_Gas-2030_exo'
      # - 'JPN09-BlueNH3_Coal-2030_exo'
      # - 'JPN09-GasCCSLeaked-2030_exo'
      # - 'JPN09-GreenH2_Gas-2030_exo'
      # - 'JPN09-GreenNH3_Coal-2030_exo'
      # - 'JPN09-BlueH2_Gas-2030_endo'
      # - 'JPN09-BlueNH3_Coal-2030_endo'
      # - 'JPN09-GasCCSLeaked-2030_endo'
      # - 'JPN09-GreenH2_Gas-2030_endo'
      # - 'JPN09-GreenNH3_Coal-2030_endo'

model_runs:
  - name: JPN_P3_JPN02
    palette: palette_1
    stock_model: Japan
    select_nodes:
      - JPN01
      - JPN02
      - JPN03
      - JPN04
      - JPN05
      - JPN06
      - JPN07
      - JPN08
      - JPN09                       
    nodes_with_ci_load:
      - JPN03
    cfe_score:
      - 0.8
      - 0.9
      - 1.0
    ci_load_fraction: 0.04 # percentage of bus-level demand that is attributed to participating C&I consumers (e.g., 0.2 = 20% of bus demand is C&I)
    allow_generation_expansion: false # if true, the model will allow generation expansion
    allow_storage_expansion: false # if true, the model will allow storage expansion
    allow_grid_expansion: false # if true, the model will allow interconnector (link) expansion
    backstop: true # if true, the model will run with a backstop technology (i.e., a generator with infinite supply potential)


technology_palette:
  #### only palette 1 is currently supported
  palette_1:
    - solar-unspecified
    - onshorewind-unspecified
    - blending-blueNH3-coal-unspecified
    - Batteries
    # - JPN02-GasCCS-2030_endo
    # - JPN02-GasCCSSequestered-2030_endo
    # - JPN02-CoalBlendBlue-2030_endo
    # - JPN02-BlueAmmonia-2030_endo
    # - JPN02-CoalBlendGreen-2030_endo
    # - JPN02-GreenAmmonia-2030_endo
    # - JPN02-GasBlendBlue-2030_endo
    # - JPN02-BlueHydrogen-2030_endo
    # - JPN02-GasBlendGreen-2030_endo
    # - JPN02-GreenHydrogen-2030_endo
    # - solar-unspecified
    # - onshorewind-unspecified
    # - Batteries
    # - gas-CCS-fossil-unspecified
    # - gas-CCS-clean-unspecified
    # - blend-coalblueammonia-fossil
    # - blend-coalblueammonia-clean
    # - blend-coalgreenammonia-fossil
    # - blend-coalgreenammonia-clean
    # - blend-gasbluehydrogen-fossil
    # - blend-gasbluehydrogen-clean
    # - blend-gasgreenhydrogen-fossil
    # - blend-gasgreenhydrogen-clean

  # palette_2:
  #   - photovoltaic-unspecified
  #   - wind-offshore-unspecified
  #   - wind-onshore
  #   - hydro-unspecified
  #   - bioenergy-unspecified
  #   - battery
  # palette_3:
  #   - photovoltaic-unspecified
  #   - wind-offshore-unspecified
  #   - wind-onshore
  #   - hydro-unspecified
  #   - bioenergy-unspecified
  #   - battery
  #   - hydrogen???

solver:
  name: gurobi
  options: gurobi-default

solver_options:
  highs-default:
    # refer to https://ergo-code.github.io/HiGHS/dev/options/definitions/
    threads: 1
    solver: "ipm"
    run_crossover: "off"
    small_matrix_value: 1e-6
    large_matrix_value: 1e9
    primal_feasibility_tolerance: 1e-5
    dual_feasibility_tolerance: 1e-5
    ipm_optimality_tolerance: 1e-4
    parallel: "on"
    random_seed: 123
  highs-simplex:
    solver: "simplex"
    parallel: "on"
    primal_feasibility_tolerance: 1e-5
    dual_feasibility_tolerance: 1e-5
    random_seed: 123
  gurobi-default:
    threads: 8
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-6
    Seed: 123
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
  gurobi-numeric-focus:
    NumericFocus: 3       # Favour numeric stability over speed
    method: 2             # barrier
    crossover: 0          # do not use crossover
    BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-4
    OptimalityTol: 1.e-4
    ObjScale: -0.5
    threads: 8
    Seed: 123
  gurobi-fallback:        # Use gurobi defaults
    crossover: 0
    method: 2             # barrier
    BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-5
    OptimalityTol: 1.e-5
    Seed: 123
    threads: 8
