# -------------------------------------------------------------------------
#
#   CONFIGS
#   
#     xxx
#
#     Authors:
#       - @amanmajid
#
# -------------------------------------------------------------------------

paths:
  output_model_runs: '../outputs/model_runs/'


global_vars:
  year: 2030
  frequency: 1h
  timesteps: 744
  set_global_constraints: false
  backstop: false
  solver: gurobi
  ci_label: c&i-ppa # this is a unique identifier for all CFE attributes in the network

model_runs:
  - name: SGP-MYS
    palette: palette_1
    core_model: ASEAN
    select_nodes:
      - MYSPE
      - MYSSK
      - MYSSH
    nodes_with_ci_load:
      - MYSPE
      - MYSSK
      - MYSSH
    ci_load_fraction: 0.1 # percentage of nodal demand is attributed to C&I
    cfe_score: 
      # percentage of C&I electricity demand that is met by carbon-free energy PPA
      # 0.50 = 50%
      - 0.75
      # - 1.00
    allow_grid_expansion: false
    backstop: false


technology_palette:
  palette_1:
    - photovoltaic-unspecified
    - wind-offshore-unspecified
    - wind-onshore
    - battery
  palette_2:
    - photovoltaic-unspecified
    - wind-offshore-unspecified
    - wind-onshore
    - hydro-unspecified
    - bioenergy-unspecified
    - battery